
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release2
        # Make resource (CPU or Memory) requests here.
        # These requests are optional, but the benefit of using them is to let the cluster manager to ensure the requirements are met for the pod
        # incl. whether a node is able to run a pod or not.
        # The request doesn't mean the pods will always need these resources, 
        # but it just means the developers stated that these are the resources the pod needs in order to run comfortably.
        # So it is always recommended.
        # resources:
        #   requests:
        #   # 1Mi = 1024Ki = 1024 * 1024 bytes. 1M = 1000K = 1,000,000 bytes.
        #     memory: 300Mi
        #   # It is important to know that if the queue started to consume 2 CPUs, it still can. These resource requests aren't limits.
        #   # The CPU requirements can have fractions, e.g. 0.5 for half CPUs, or 100m for 0.1 CPUs
        #     cpu: 100m
---
# Because this position-simulator is purely a message generator, we do not need to interact with it, so we don' need a k8s service for it.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release2
        env:
        # env for "environmental variables", which are Application-specific configurations used by the spring boot application
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  selector:
    matchLabels:
      app: position-tracker
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release3
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

        
